name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
  
jobs:
  build-and-test-windows-latest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Software Versions
        run: |
          echo "CMake Version:"
          cmake --version
          echo "GCC Version:"
          gcc --version
          echo "G++ Version:"
          g++ --version
          echo "Ninja Version:"
          ninja --version

      - name: Configure
        run: cmake --preset gcc-debug

      - name: Build
        run: cmake --build --preset gcc-debug --parallel

      - name: Test
        run: ctest --preset gcc-debug --output-on-failure --verbose

      - name: Publish build artifacts if failed
        if: true
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows-latest
          path: build/gcc-debug/
  
  build-and-test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Software Versions
        run: |
          echo "CMake Version:"
          cmake --version
          echo "GCC Version:"
          gcc --version
          echo "G++ Version:"
          g++ --version
          echo "Ninja Version:"
          ninja --version

      - name: Configure
        run: cmake --preset gcc-debug

      - name: Build
        run: cmake --build --preset gcc-debug --parallel

      - name: Test
        run: ctest --preset gcc-debug --output-on-failure --verbose

      - name: Publish build artifacts if failed
        if: true
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-ubuntu-latest
          path: build/gcc-debug/

  build-and-test-macos-latest:
    runs-on: macos-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Software Versions
        run: |
          echo "CMake Version:"
          cmake --version
          echo "GCC Version:"
          gcc --version
          echo "G++ Version:"
          g++ --version
          echo "Ninja Version:"
          ninja --version
